[project]
name = "cinetix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "Navraj Kalsi", email = "navrajkalsi@icloud.com" }]
dependencies = [
  "fastapi[standard]>=0.141.1",
  "psycopg2>=2.9.12",
  "sqlmodel>=0.0.42",
]

[project.scripts]
cinetix = "cinetix:main"

[dependency-groups]
dev = [
  "basedpyright>=1.39.10",
  "ruff>=0.16.6",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
