[project]
name = "cinetix"
version = "0.1.0"
description = "Add your description here"
readme = "./../README.md"
requires-python = ">=3.14"
authors = [{ name = "Navraj Kalsi", email = "navrajkalsi@icloud.com" }]
dependencies = [
  "fastapi[all]>=0.141.1",
  "psycopg2>=2.9.12",
  "pypdf[image]>=6.19.0",
  "pytesseract>=0.3.13",
  "pytest>=9.1.1",
  "requests>=2.34.2",
  "sqlmodel>=0.0.42",
]

[project.scripts]
create = "scripts:create_booking"
pdf = "pdf:from_args"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "src.api:app"

[tool.pytest]
# https://docs.pytest.org/en/stable/reference/reference.html#command-line-flags
addopts = ["-ra", "-q"]
minversion = "9.0"
testpaths = [
  "integration",
  "tests",
]

[tool.uv]
package = true
