import datetime
from decimal import Decimal

from pydantic import model_validator
from sqlalchemy import String
from sqlalchemy.dialects.postgresql import ARRAY
from sqlmodel import CheckConstraint, Field, SQLModel


class BookingBase(SQLModel):
    """Fields shared by every booking model.

    The model is validated to always have an `external_id` if not `added_manually`.
    """

    # Users may find it inconvenient if this field was required when entering data manually
    external_id: str | None = Field(
        default=None,
        min_length=1,
        description="Booking ID from the movie theater chain.",
    )
    date: datetime.date = Field(description="Date of the showing.")
    time: datetime.time | None = Field(
        default=None,
        description="Time of the showing on `date` with no timezone information.",
    )
    seats: list[str] | None = Field(
        default=None,
        min_length=1,
        sa_type=ARRAY(String),
        description="List of seats with each seat being a row and seat number.",
    )
    price: Decimal | None = Field(
        default=None,
        ge=0,
        decimal_places=2,
        description="Price of the booking in local currency.",
    )
    movie_id: int = Field(
        foreign_key="movies.id", description="ID of the movie already in the database."
    )
    location_id: int = Field(
        foreign_key="locations.id",
        description="ID of the location already in the database.",
    )
    format_id: int = Field(
        foreign_key="formats.id",
        description="ID of the format already in the database.",
    )
    added_manually: bool = Field(
        default=True,
        description="Was this booking information entered manually by the user or auto generated by the email client.",
    )

    @model_validator(mode="after")
    def validate_external_id(self):
        if not self.added_manually and self.external_id is None:
            raise ValueError("auto generated booking must contain the external_id")

        return self


class BookingCreate(BookingBase):
    """Request body for creating a booking."""


class Booking(BookingBase, table=True):
    """A row in the `bookings` table.

    The table is constraint to always require `external_id` when `added_manually` is not `True`.
    This is to make sure that `external_id` is always received from the email client but the user
    may choose to not enter it.
    """

    __tablename__ = "bookings"

    __table_args__ = (
        CheckConstraint(
            "added_manually OR external_id IS NOT NULL",
            name="check_external_id_for_auto_added",
        ),
    )

    id: int | None = Field(default=None, primary_key=True)


class BookingRead(BookingBase):
    """Response body for quering a booking from the database."""

    id: int
